# Generated by Django 3.1.6 on 2021-02-08 00:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 0, 22, 55, 90977, tzinfo=utc), verbose_name='date published'),
        ),
    ]
