# Generated by Django 3.1.6 on 2021-02-08 00:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 2, 8, 0, 23, 5, 908778, tzinfo=utc)),
        ),
    ]
