# Generated by Django 3.1.6 on 2021-02-19 00:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210208_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2021, 2, 19, 0, 41, 8, 647170, tzinfo=utc)),
        ),
    ]
