# Generated by Django 3.1.7 on 2021-05-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210313_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Decline', 'Decline')], default='Pending', max_length=50),
        ),
    ]
